### ISSUE TITLE
AdGuard DNS

### ISSUE THREAD

**Issue by warengonzaga** [warengonzaga/wrn-fix-it#4]
Add AdGuard DNS in the DNS changer tool. 😎

**Comment by WarenGonzaga** [comment]
DNS hostname to add:

AdGuard (Default)
``94.140.14.14``
``94.140.15.15``

AdGuard (Family)
``94.140.14.15``
``94.140.15.16``

AdGuard (Non-Filtering)
``94.140.14.140``
``94.140.14.141``

**Comment by WarenGonzaga** [comment]
Implemented in bash script version here: https://github.com/WarenGonzaga/wrn-fix-it/pull/13

**Comment by WarenGonzaga** [comment]
Implemented in Python version here: https://github.com/WarenGonzaga/wrn-fix-it/pull/15
Good move @angelofallars for adding error checking using regex.
